// Auto-generated by build_biz_path_audio_data.py - Business Path audio models
window.BIZ_PATH_DATA = {
  "b1": {
    "tag": "Office Foundations (B1)",
    "icon": "fa-briefcase",
    "sub": "Business Path I (B1)",
    "crumb": "Business Path I",
    "lessons": [
      {
        "n": 1,
        "title": "Introductions & Networking Basics",
        "file": "corporate_b1_l01.mp3",
        "icon": "fa-handshake"
      },
      {
        "n": 2,
        "title": "Phone Calls that Work",
        "file": "corporate_b1_l02.mp3",
        "icon": "fa-handshake"
      },
      {
        "n": 3,
        "title": "Professional Emails 101",
        "file": "corporate_b1_l03.mp3",
        "icon": "fa-handshake"
      },
      {
        "n": 4,
        "title": "Small Talk & Rapport",
        "file": "corporate_b1_l04.mp3",
        "icon": "fa-handshake"
      },
      {
        "n": 5,
        "title": "Scheduling & Rescheduling",
        "file": "corporate_b1_l05.mp3",
        "icon": "fa-gears"
      },
      {
        "n": 6,
        "title": "Polite Requests & Favors",
        "file": "corporate_b1_l06.mp3",
        "icon": "fa-gears"
      },
      {
        "n": 7,
        "title": "Explaining a Process",
        "file": "corporate_b1_l07.mp3",
        "icon": "fa-gears"
      },
      {
        "n": 8,
        "title": "Reporting a Problem & Asking for Help",
        "file": "corporate_b1_l08.mp3",
        "icon": "fa-gears"
      },
      {
        "n": 9,
        "title": "Meeting Survival Kit",
        "file": "corporate_b1_l09.mp3",
        "icon": "fa-people-group"
      },
      {
        "n": 10,
        "title": "Opinions & Suggestions",
        "file": "corporate_b1_l10.mp3",
        "icon": "fa-people-group"
      },
      {
        "n": 11,
        "title": "Status Updates & Standups",
        "file": "corporate_b1_l11.mp3",
        "icon": "fa-people-group"
      },
      {
        "n": 12,
        "title": "Delegating & Offering Help",
        "file": "corporate_b1_l12.mp3",
        "icon": "fa-people-group"
      },
      {
        "n": 13,
        "title": "Customer Service Calls",
        "file": "corporate_b1_l13.mp3",
        "icon": "fa-headset"
      },
      {
        "n": 14,
        "title": "Handling Complaints",
        "file": "corporate_b1_l14.mp3",
        "icon": "fa-headset"
      },
      {
        "n": 15,
        "title": "Orders, Invoices & Deliveries",
        "file": "corporate_b1_l15.mp3",
        "icon": "fa-headset"
      },
      {
        "n": 16,
        "title": "The Service Recovery Email",
        "file": "corporate_b1_l16.mp3",
        "icon": "fa-headset"
      },
      {
        "n": 17,
        "title": "Job Interview Basics",
        "file": "corporate_b1_l17.mp3",
        "icon": "fa-user-tie"
      },
      {
        "n": 18,
        "title": "Talking About Your Experience",
        "file": "corporate_b1_l18.mp3",
        "icon": "fa-user-tie"
      },
      {
        "n": 19,
        "title": "The Performance Check-in",
        "file": "corporate_b1_l19.mp3",
        "icon": "fa-user-tie"
      },
      {
        "n": 20,
        "title": "Capstone: A Full Office Day",
        "file": "corporate_b1_l20.mp3",
        "icon": "fa-flag-checkered"
      }
    ]
  },
  "c1": {
    "tag": "Strategic Influence (C1)",
    "icon": "fa-crown",
    "sub": "Business Path III (C1)",
    "crumb": "Business Path III",
    "lessons": [
      {
        "n": 1,
        "title": "The Architecture of Influence",
        "file": "corporate_c1_l01.mp3",
        "icon": "fa-wand-magic-sparkles"
      },
      {
        "n": 2,
        "title": "Framing & Reframing",
        "file": "corporate_c1_l02.mp3",
        "icon": "fa-wand-magic-sparkles"
      },
      {
        "n": 3,
        "title": "Storytelling for Business Impact",
        "file": "corporate_c1_l03.mp3",
        "icon": "fa-wand-magic-sparkles"
      },
      {
        "n": 4,
        "title": "Data Storytelling & the So-What Test",
        "file": "corporate_c1_l04.mp3",
        "icon": "fa-wand-magic-sparkles"
      },
      {
        "n": 5,
        "title": "Diplomatic Language & Hedging",
        "file": "corporate_c1_l05.mp3",
        "icon": "fa-dove"
      },
      {
        "n": 6,
        "title": "Conflict Management Conversations",
        "file": "corporate_c1_l06.mp3",
        "icon": "fa-dove"
      },
      {
        "n": 7,
        "title": "Feedback at the Top",
        "file": "corporate_c1_l07.mp3",
        "icon": "fa-dove"
      },
      {
        "n": 8,
        "title": "Cross-Cultural & Global Leadership",
        "file": "corporate_c1_l08.mp3",
        "icon": "fa-dove"
      },
      {
        "n": 9,
        "title": "Anchors & Openings",
        "file": "corporate_c1_l09.mp3",
        "icon": "fa-scale-balanced"
      },
      {
        "n": 10,
        "title": "Concessions & Trades",
        "file": "corporate_c1_l10.mp3",
        "icon": "fa-scale-balanced"
      },
      {
        "n": 11,
        "title": "Deadlock, BATNA & Walking Away",
        "file": "corporate_c1_l11.mp3",
        "icon": "fa-scale-balanced"
      },
      {
        "n": 12,
        "title": "Multi-Party & Internal Negotiation",
        "file": "corporate_c1_l12.mp3",
        "icon": "fa-scale-balanced"
      },
      {
        "n": 13,
        "title": "Executive Presence & High-Impact Speaking",
        "file": "corporate_c1_l13.mp3",
        "icon": "fa-crown"
      },
      {
        "n": 14,
        "title": "Boardroom & Stakeholder Communication",
        "file": "corporate_c1_l14.mp3",
        "icon": "fa-crown"
      },
      {
        "n": 15,
        "title": "Debating Complex Ideas & Defending Positions",
        "file": "corporate_c1_l15.mp3",
        "icon": "fa-crown"
      },
      {
        "n": 16,
        "title": "Q&A Under Fire & Crisis Communication",
        "file": "corporate_c1_l16.mp3",
        "icon": "fa-crown"
      },
      {
        "n": 17,
        "title": "Crisis Simulation: The First 24 Hours",
        "file": "corporate_c1_l17.mp3",
        "icon": "fa-flag-checkered"
      },
      {
        "n": 18,
        "title": "Global Leadership Scenario",
        "file": "corporate_c1_l18.mp3",
        "icon": "fa-flag-checkered"
      },
      {
        "n": 19,
        "title": "The Persuasive Sales Pitch I: Design",
        "file": "corporate_c1_l19.mp3",
        "icon": "fa-flag-checkered"
      },
      {
        "n": 20,
        "title": "The Persuasive Sales Pitch II: Deliver & Close (Capstone)",
        "file": "corporate_c1_l20.mp3",
        "icon": "fa-flag-checkered"
      }
    ]
  }
};
