// Auto-generated by _scripts/political/build_political_audio_data.py
// Political & Global Affairs listening tracks (audio_library.html).
window.POLITICAL_AUDIO_DATA = {
  "tag": "Diplomacy, Policy & Civil Discourse",
  "sub": "Political & Global Affairs (B2-C1)",
  "crumb": "Political & Global Affairs",
  "icon": "fa-landmark",
  "course": "political_english",
  "lessons": [
    {
      "n": 1,
      "title": "Leaders & Roles",
      "file": "political_english_l01.mp3",
      "icon": "fa-sitemap",
      "badge": "Institutions",
      "module": "The Machinery of the State"
    },
    {
      "n": 2,
      "title": "Government Buildings",
      "file": "political_english_l02.mp3",
      "icon": "fa-landmark",
      "badge": "Institutions",
      "module": "The Machinery of the State"
    },
    {
      "n": 3,
      "title": "Signs & Laws",
      "file": "political_english_l03.mp3",
      "icon": "fa-scale-balanced",
      "badge": "Legal register",
      "module": "The Machinery of the State"
    },
    {
      "n": 4,
      "title": "Branches of Power",
      "file": "political_english_l04.mp3",
      "icon": "fa-code-branch",
      "badge": "Institutions",
      "module": "The Machinery of the State"
    },
    {
      "n": 5,
      "title": "Tax & Spend",
      "file": "political_english_l05.mp3",
      "icon": "fa-coins",
      "badge": "Policy",
      "module": "The Machinery of the State"
    },
    {
      "n": 6,
      "title": "Breaking News",
      "file": "political_english_l06.mp3",
      "icon": "fa-newspaper",
      "badge": "Media",
      "module": "The Language of Power"
    },
    {
      "n": 7,
      "title": "Protests & Rights",
      "file": "political_english_l07.mp3",
      "icon": "fa-bullhorn",
      "badge": "Civil society",
      "module": "The Language of Power"
    },
    {
      "n": 8,
      "title": "Globalization & Trade",
      "file": "political_english_l08.mp3",
      "icon": "fa-ship",
      "badge": "Economics",
      "module": "The Language of Power"
    },
    {
      "n": 9,
      "title": "Soft Power",
      "file": "political_english_l09.mp3",
      "icon": "fa-handshake-angle",
      "badge": "Diplomacy",
      "module": "The Language of Power"
    },
    {
      "n": 10,
      "title": "Treaties & Law",
      "file": "political_english_l10.mp3",
      "icon": "fa-file-signature",
      "badge": "Legal register",
      "module": "The Language of Power"
    },
    {
      "n": 11,
      "title": "Crisis Management",
      "file": "political_english_l11.mp3",
      "icon": "fa-tower-broadcast",
      "badge": "Communication",
      "module": "The Language of Power"
    },
    {
      "n": 12,
      "title": "Election Day",
      "file": "political_english_l12.mp3",
      "icon": "fa-check-to-slot",
      "badge": "Elections",
      "module": "The Democratic Contest"
    },
    {
      "n": 13,
      "title": "Political Parties",
      "file": "political_english_l13.mp3",
      "icon": "fa-people-group",
      "badge": "Elections",
      "module": "The Democratic Contest"
    },
    {
      "n": 14,
      "title": "The Campaign Trail",
      "file": "political_english_l14.mp3",
      "icon": "fa-microphone-lines",
      "badge": "Rhetoric",
      "module": "The Democratic Contest"
    },
    {
      "n": 15,
      "title": "Public Opinion & Polling",
      "file": "political_english_l15.mp3",
      "icon": "fa-chart-pie",
      "badge": "Data",
      "module": "The Democratic Contest"
    },
    {
      "n": 16,
      "title": "Scandals & Ethics",
      "file": "political_english_l16.mp3",
      "icon": "fa-magnifying-glass",
      "badge": "Accountability",
      "module": "The Democratic Contest"
    },
    {
      "n": 17,
      "title": "Nations & Borders",
      "file": "political_english_l17.mp3",
      "icon": "fa-map",
      "badge": "Geopolitics",
      "module": "Global Fault Lines"
    },
    {
      "n": 18,
      "title": "Environmental Policy",
      "file": "political_english_l18.mp3",
      "icon": "fa-leaf",
      "badge": "Policy",
      "module": "Global Fault Lines"
    },
    {
      "n": 19,
      "title": "Immigration & Borders",
      "file": "political_english_l19.mp3",
      "icon": "fa-passport",
      "badge": "Policy",
      "module": "Global Fault Lines"
    },
    {
      "n": 20,
      "title": "The Social Contract",
      "file": "political_english_l20.mp3",
      "icon": "fa-scroll",
      "badge": "Philosophy",
      "module": "Global Fault Lines"
    },
    {
      "n": 21,
      "title": "Geopolitics: The Silicon Shield",
      "file": "political_english_l21.mp3",
      "icon": "fa-microchip",
      "badge": "Geopolitics",
      "module": "Global Fault Lines"
    }
  ]
};
