// Auto-generated by _scripts/political/build_political_cues.py
// Subtitle cues for the Political & Global Affairs tracks, recovered
// from the shipped mp3s (see that script for how, and why not from
// the generator). t/e are seconds, s is the speaker, x the line.
// lesson.html shows its subtitle panel only for keys present here.
window.POLITICAL_CUES = {
 "political_english_l01.mp3": [
  {
   "e": 7.78,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson one: Leaders and Roles."
  },
  {
   "e": 16.2,
   "s": "Halloran (The Sentinel)",
   "t": 7.78,
   "x": "Minister, before we start — am I speaking to you as Minister for Water and Energy, or as chair of Marenta's accession working group with the Coastal Union?"
  },
  {
   "e": 26.86,
   "s": "Minister Adeyemi",
   "t": 16.2,
   "x": "Both hats are on the table, but for the next twenty minutes treat me as the Minister. The working group has its own spokesperson, and I'd rather not do her job for her."
  },
  {
   "e": 31.94,
   "s": "Halloran (The Sentinel)",
   "t": 26.86,
   "x": "Then let's begin there. Who signed off on the Velenia transit licence?"
  },
  {
   "e": 41.57,
   "s": "Minister Adeyemi",
   "t": 31.94,
   "x": "The licence was issued under delegated authority by the Director-General of the Water Agency. My name is on the policy, not on the instrument."
  },
  {
   "e": 43.85,
   "s": "Halloran (The Sentinel)",
   "t": 41.57,
   "x": "So it wasn't your decision."
  },
  {
   "e": 54.22,
   "s": "Minister Adeyemi",
   "t": 43.85,
   "x": "It fell within her remit. I set the framework; she applies it. If you want the file, you refer up to me. If you want the signature, you go to her."
  },
  {
   "e": 68.74,
   "s": "Vondra (Coastal Union secretariat)",
   "t": 54.22,
   "x": "May I come in on that? From the Union's side, Marenta is a candidate and not a member, so a licence issued in Marenta binds nobody inside the bloc. Our parliament would have to legislate separately, and it has not."
  },
  {
   "e": 72.74,
   "s": "Halloran (The Sentinel)",
   "t": 68.74,
   "x": "Deputy Director Vondra, are you speaking for the six governments?"
  },
  {
   "e": 85.94,
   "s": "Vondra (Coastal Union secretariat)",
   "t": 72.74,
   "x": "I'm speaking in my capacity as secretariat, which means I can describe the procedure and nothing else. The governments speak for themselves, and, as you well know, they rarely say the same thing on the same day."
  },
  {
   "e": 91.1,
   "s": "Halloran (The Sentinel)",
   "t": 85.94,
   "x": "Minister, The Sentinel has been told the Director-General intends to step down this month."
  },
  {
   "e": 100.63,
   "s": "Minister Adeyemi",
   "t": 91.1,
   "x": "I won't comment on an individual's future. What I will say is that the post is answerable to the Assembly's Resources Committee, whoever holds it."
  },
  {
   "e": 109.68,
   "s": "Halloran (The Sentinel)",
   "t": 100.63,
   "x": "Supporters call her a safe pair of hands. Critics counter that she is far too close to the industry she licenses. Which is it?"
  },
  {
   "e": 119.28,
   "s": "Minister Adeyemi",
   "t": 109.68,
   "x": "That's a judgement for the Committee, not for me. My job this afternoon is to tell you where the decision sat, and it sat with the Agency."
  },
  {
   "e": 126.38,
   "s": "Halloran (The Sentinel)",
   "t": 119.28,
   "x": "One last thing. If she stands aside next week and hands over to her deputy, does the licence still stand?"
  },
  {
   "e": 132.36,
   "s": "Minister Adeyemi",
   "t": 126.38,
   "x": "It stands. The authority attaches to the office, not to the person."
  }
 ],
 "political_english_l02.mp3": [
  {
   "e": 7.85,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson Two: Government Buildings."
  },
  {
   "e": 17.74,
   "s": "Farrow (The Sentinel)",
   "t": 7.85,
   "x": "Minister, Rosewater House confirmed overnight that the east side of the Cordera Chamber will be sealed off for a structural survey. Is Marenta's parliament leaving the hill?"
  },
  {
   "e": 28.78,
   "s": "Minister Adeyemi",
   "t": 17.74,
   "x": "The Chamber is not leaving anywhere. A survey is a survey. I would be careful about letting a building stand for a decision that nobody has taken."
  },
  {
   "e": 34.18,
   "s": "Farrow (The Sentinel)",
   "t": 28.78,
   "x": "Then who took the decision to look at office space for the ministerial wing at Port Vellis?"
  },
  {
   "e": 38.86,
   "s": "Minister Adeyemi",
   "t": 34.18,
   "x": "What I can speak to is the process, not the position."
  },
  {
   "e": 48.48,
   "s": "Vance (Ministry spokesperson)",
   "t": 38.86,
   "x": "To be precise, the survey was commissioned by the Chamber itself, not by Rosewater House. The two buildings are not in disagreement."
  },
  {
   "e": 63.19,
   "s": "Farrow (The Sentinel)",
   "t": 48.48,
   "x": "The Coastal Union sat in temporary premises for four years, and its own political correspondents say its parliament never recovered the habit of meeting in plenary. Velenia has never left the Glass Ministry. Which model is Marenta following?"
  },
  {
   "e": 76.61,
   "s": "Minister Adeyemi",
   "t": 63.19,
   "x": "Supporters of a purpose-built chamber argue that a safe roof is worth more than a famous staircase. Critics counter that the seat of government carries a meaning a new building cannot inherit."
  },
  {
   "e": 85.61,
   "s": "Vance (Ministry spokesperson)",
   "t": 76.61,
   "x": "And the public gallery stays open for every sitting during the works. Nothing here is being handled behind closed doors."
  },
  {
   "e": 90.86,
   "s": "Farrow (The Sentinel)",
   "t": 85.61,
   "x": "Off the record, Minister. Is the Ministry shoring up support for a move before the vote?"
  },
  {
   "e": 94.82,
   "s": "Minister Adeyemi",
   "t": 90.86,
   "x": "On the record: no decision has been taken at this stage."
  },
  {
   "e": 103.27,
   "s": "Minister Adeyemi",
   "t": 94.82,
   "x": "When I last spoke on the floor I gave way twice to members from Port Vellis, and neither of them asked me about the roof."
  },
  {
   "e": 113.4,
   "s": "Minister Adeyemi",
   "t": 103.27,
   "x": "Speaking in a personal capacity, I have spent nineteen years in the corridors of power at Rosewater House, and I would not hand over that building lightly."
  },
  {
   "e": 118.73,
   "s": "Farrow (The Sentinel)",
   "t": 113.4,
   "x": "May I quote the corridors of power line, or was that the man rather than the Ministry?"
  },
  {
   "e": 123.6,
   "s": "Minister Adeyemi",
   "t": 118.73,
   "x": "That was the man. Quote the Ministry for anything that matters."
  },
  {
   "e": 138.91,
   "s": "Vance (Ministry spokesperson)",
   "t": 123.6,
   "x": "There is a background briefing at three, unattributable as always, and the press briefing room opens at four. The Chamber's own statement goes first; the private office will not be adding to it, and we take your questions after that."
  }
 ],
 "political_english_l03.mp3": [
  {
   "e": 16.15,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson three: Signs and Laws. A press briefing at the Ministry of Water and Energy in Marenta, three days before the Site Notices Regulation is signed off."
  },
  {
   "e": 25.7,
   "s": "Farrow (The Sentinel)",
   "t": 16.15,
   "x": "Minister, Article 4 of the draft says operators shall display the hazard notice in both official languages. Is that a requirement or an aspiration?"
  },
  {
   "e": 35.04,
   "s": "Minister Adeyemi",
   "t": 25.7,
   "x": "It is a provision this Ministry takes extremely seriously, and one that reflects twelve years of steady progress on site safety."
  },
  {
   "e": 39.48,
   "s": "Farrow (The Sentinel)",
   "t": 35.04,
   "x": "That isn't an answer. Requirement, or aspiration?"
  },
  {
   "e": 48.22,
   "s": "Renko (Coastal Union legal service)",
   "t": 39.48,
   "x": "If I may. In this text, shall is strictly obligatory. Article 4 leaves the operator no discretion whatsoever."
  },
  {
   "e": 53.09,
   "s": "Farrow (The Sentinel)",
   "t": 48.22,
   "x": "Then why does Article 5 say the Ministry may require a third language?"
  },
  {
   "e": 60.31,
   "s": "Renko (Coastal Union legal service)",
   "t": 53.09,
   "x": "Because may creates a power, not a duty. The Ministry can act; nothing in Article 5 obliges it to."
  },
  {
   "e": 77.28,
   "s": "Minister Adeyemi",
   "t": 60.31,
   "x": "And for the record, this Ministry has no present intention of invoking Article 5. I would add that the duty in Article 4 is phased in: operators with fewer than fifty staff have eighteen months from the date the regulation enters into force."
  },
  {
   "e": 80.88,
   "s": "Farrow (The Sentinel)",
   "t": 77.28,
   "x": "Eighteen months in which a hazard sign can sit in a drawer."
  },
  {
   "e": 92.4,
   "s": "Minister Adeyemi",
   "t": 80.88,
   "x": "Eighteen months in which businesses order, translate and mount signage that has to survive twenty years of salt air. That is not delay, it is procurement."
  },
  {
   "e": 96.36,
   "s": "Farrow (The Sentinel)",
   "t": 92.4,
   "x": "What happens to an operator who simply takes a notice down?"
  },
  {
   "e": 107.93,
   "s": "Renko (Coastal Union legal service)",
   "t": 96.36,
   "x": "Article 6 is prohibitive: no operator shall remove or obscure a posted notice. In plain English, must not — and that one carries a fine from day one, with no phase-in."
  },
  {
   "e": 118.3,
   "s": "Farrow (The Sentinel)",
   "t": 107.93,
   "x": "Industry associations call the bilingual requirement an unfunded burden on small firms. Safety inspectors call it ten years overdue. Which is it, Minister?"
  },
  {
   "e": 133.87,
   "s": "Minister Adeyemi",
   "t": 118.3,
   "x": "Both cases have been argued at length and both are on the public record. What I can tell you is that this Ministry will comply with the letter of the law from the day it enters into force, and will expect the same of everyone else."
  },
  {
   "e": 137.11,
   "s": "Farrow (The Sentinel)",
   "t": 133.87,
   "x": "Including the state-owned port operator at Kessin?"
  },
  {
   "e": 144.84,
   "s": "Minister Adeyemi",
   "t": 137.11,
   "x": "The text says operators. It does not say private operators. I will leave you to draw the conclusion."
  }
 ],
 "political_english_l04.mp3": [
  {
   "e": 7.7,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson four: Branches of Power."
  },
  {
   "e": 18.07,
   "s": "Brennell (The Sentinel)",
   "t": 7.7,
   "x": "Minister, the Assembly's resources committee approved your royalties decree in eleven minutes. Eleven. Is that committee anything more than a rubber stamp?"
  },
  {
   "e": 28.13,
   "s": "Minister Adeyemi",
   "t": 18.07,
   "x": "The committee exercised its oversight function within the time it judged sufficient. Speed is not the same thing as deference."
  },
  {
   "e": 30.46,
   "s": "Brennell (The Sentinel)",
   "t": 28.13,
   "x": "Eleven minutes, Minister."
  },
  {
   "e": 37.82,
   "s": "Minister Adeyemi",
   "t": 30.46,
   "x": "Members had the draft for three weeks before the sitting. What you are timing is the vote, not the scrutiny."
  },
  {
   "e": 50.95,
   "s": "Chair Dessane",
   "t": 37.82,
   "x": "May I come in there. The committee did not write the decree and it cannot rewrite it. Under the 2019 mining act we either wave it through or send it back whole."
  },
  {
   "e": 55.2,
   "s": "Brennell (The Sentinel)",
   "t": 50.95,
   "x": "So the ministry makes the rules and the committee gets a yes-or-no button."
  },
  {
   "e": 66.74,
   "s": "Chair Dessane",
   "t": 55.2,
   "x": "The ministry applies powers the Assembly delegated to it. If that delegation was drawn too wide, it is the Assembly's mistake to fix, not this committee's."
  },
  {
   "e": 76.39,
   "s": "Minister Adeyemi",
   "t": 66.74,
   "x": "And it is being examined. Velenia's investors asked the same question at the Coastal Union summit last month, and I gave them the same answer."
  },
  {
   "e": 85.37,
   "s": "Brennell (The Sentinel)",
   "t": 76.39,
   "x": "Minister, the Constitutional Court has now agreed to hear the challenge. If it strikes down the royalties article, what happens on Monday morning?"
  },
  {
   "e": 96.91,
   "s": "Minister Adeyemi",
   "t": 85.37,
   "x": "Then the article falls and we go back to the Assembly for enabling legislation. A ruling of that court is binding on this ministry whatever our view of it."
  },
  {
   "e": 99.89,
   "s": "Brennell (The Sentinel)",
   "t": 96.91,
   "x": "You would accept it? Personally?"
  },
  {
   "e": 112.01,
   "s": "Minister Adeyemi",
   "t": 99.89,
   "x": "We would apply it. That is what the executive does - it applies; the Assembly makes; the Court judges. I would rather the three were not confused on your front page."
  },
  {
   "e": 119.42,
   "s": "Chair Dessane",
   "t": 112.01,
   "x": "And if the Court upholds the delegation, this committee will still be asking why eleven minutes looked like enough."
  },
  {
   "e": 121.92,
   "s": "Brennell (The Sentinel)",
   "t": 119.42,
   "x": "Chair, is that on the record?"
  },
  {
   "e": 128.52,
   "s": "Chair Dessane",
   "t": 121.92,
   "x": "On the record. Oversight is not obstruction, and it is not applause either."
  }
 ],
 "political_english_l05.mp3": [
  {
   "e": 15.94,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson five: Tax and Spend. Minister Adeyemi and Budget Director Reyner take questions from Dalia Ferrand of The Sentinel on Marenta's new water levy."
  },
  {
   "e": 22.94,
   "s": "Ferrand",
   "t": 15.94,
   "x": "Minister, the levy raises four hundred million marena a year. Where exactly does it go?"
  },
  {
   "e": 30.62,
   "s": "Adeyemi",
   "t": 22.94,
   "x": "It's ring-fenced. Every marena raised sits in a separate account and can only be spent on the pipe network."
  },
  {
   "e": 34.42,
   "s": "Ferrand",
   "t": 30.62,
   "x": "Ring-fenced by law, or ring-fenced by promise?"
  },
  {
   "e": 42.22,
   "s": "Adeyemi",
   "t": 34.42,
   "x": "By statute. The Budget Office signs off on each release, and the accounts are published every quarter."
  },
  {
   "e": 49.03,
   "s": "Reyner",
   "t": 42.22,
   "x": "I'd add that the levy is phased in over three years — one third, two thirds, then the full rate."
  },
  {
   "e": 60.74,
   "s": "Ferrand",
   "t": 49.03,
   "x": "Critics in the Coastal Union parliament say a flat levy hits low earners hardest. Supporters say it's the only honest way to broaden the tax base. Which is it?"
  },
  {
   "e": 71.4,
   "s": "Adeyemi",
   "t": 60.74,
   "x": "Both arguments are on the table, and I'm not going to pretend otherwise. That is precisely why the first two hundred units of household use are exempt."
  },
  {
   "e": 77.76,
   "s": "Ferrand",
   "t": 71.4,
   "x": "Velenia funded the same repairs out of general taxation and needed no levy at all."
  },
  {
   "e": 85.46,
   "s": "Adeyemi",
   "t": 77.76,
   "x": "Velenia has fiscal headroom that we don't. We have to balance the books with the revenue we actually collect."
  },
  {
   "e": 89.59,
   "s": "Ferrand",
   "t": 85.46,
   "x": "So is this new money, or money moved from somewhere else?"
  },
  {
   "e": 99.07,
   "s": "Reyner",
   "t": 89.59,
   "x": "New, in the sense that it wasn't there last year. But recurrent expenditure across the ministry is flat — we haven't grown the department on the back of it."
  },
  {
   "e": 102.5,
   "s": "Ferrand",
   "t": 99.07,
   "x": "And if collection comes in below forecast?"
  },
  {
   "e": 109.94,
   "s": "Adeyemi",
   "t": 102.5,
   "x": "Then we scale back the third-year works and we say so publicly. I'm not going to promise a schedule I can't fund."
  },
  {
   "e": 114.07,
   "s": "Ferrand",
   "t": 109.94,
   "x": "Has anyone put a figure on not repairing the network at all?"
  },
  {
   "e": 122.59,
   "s": "Reyner",
   "t": 114.07,
   "x": "Eight hundred million over a decade, in lost water and emergency repairs. The cost of doing nothing is also a number."
  }
 ],
 "political_english_l06.mp3": [
  {
   "e": 7.68,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson six: Breaking News."
  },
  {
   "e": 20.64,
   "s": "Halloran (The Sentinel)",
   "t": 7.68,
   "x": "Mr Ferreiro, we file in forty minutes. The audit of Marenta's mining licences went onto the ministry portal at 18:40 on Friday, the eve of a public holiday. Was that timing deliberate?"
  },
  {
   "e": 28.75,
   "s": "Ferreiro (Ministry spokesman)",
   "t": 20.64,
   "x": "The document was published as soon as it cleared legal review. I'd push back on any suggestion of stage-management."
  },
  {
   "e": 39.89,
   "s": "Halloran (The Sentinel)",
   "t": 28.75,
   "x": "Then let me put the top line to you, and you can correct it. Twenty-two of the ninety licences were awarded without the required environmental sign-off. Do you dispute the figure?"
  },
  {
   "e": 50.86,
   "s": "Ferreiro (Ministry spokesman)",
   "t": 39.89,
   "x": "I'd characterise it differently. Twenty-two files show incomplete documentation. That is not the same thing as a licence being awarded improperly."
  },
  {
   "e": 58.97,
   "s": "Halloran (The Sentinel)",
   "t": 50.86,
   "x": "Understood. I'll attribute that wording to you directly, so 'incomplete documentation' appears as your phrase, not mine."
  },
  {
   "e": 63.41,
   "s": "Ferreiro (Ministry spokesman)",
   "t": 58.97,
   "x": "You can say the ministry accepts the count and rejects the inference."
  },
  {
   "e": 71.57,
   "s": "Adeyemi (Minister for Water and Energy)",
   "t": 63.41,
   "x": "Ms Halloran, before you run with that lede — the audit was commissioned by this ministry. Nobody dragged it out of us."
  },
  {
   "e": 83.47,
   "s": "Halloran (The Sentinel)",
   "t": 71.57,
   "x": "Noted, Minister, and it'll be in the third paragraph. But it doesn't displace the top line: twenty-two files, no sign-off. That is what the reader needs in sentence one."
  },
  {
   "e": 90.86,
   "s": "Adeyemi (Minister for Water and Energy)",
   "t": 83.47,
   "x": "Your sentence one will be read aloud in the Coastal Union parliament by Tuesday. I'd ask you to weigh the wording."
  },
  {
   "e": 105.22,
   "s": "Halloran (The Sentinel)",
   "t": 90.86,
   "x": "I'll weigh it; I won't soften it. Supporters of the licensing reform will say the audit proves the system corrects itself. Critics will say it proves the checks were never enforced. I carry both, sourced."
  },
  {
   "e": 112.37,
   "s": "Ferreiro (Ministry spokesman)",
   "t": 105.22,
   "x": "Then attribute the second to whom, precisely? Unnamed critics are a curtain to hide behind."
  },
  {
   "e": 119.78,
   "s": "Halloran (The Sentinel)",
   "t": 112.37,
   "x": "Fair. I name them or I cut them. I'm not printing 'a source close to the ministry' for an attack on the ministry."
  },
  {
   "e": 125.35,
   "s": "Halloran (The Sentinel)",
   "t": 119.78,
   "x": "Last thing, Minister. One line on the record about the Friday evening timing?"
  },
  {
   "e": 139.1,
   "s": "Adeyemi (Minister for Water and Energy)",
   "t": 125.35,
   "x": "On the record: the publication time was set by the legal clearance calendar, not by the news cycle. Velenia released its own audit on a Saturday last year and nobody accused it of burying a story."
  },
  {
   "e": 146.28,
   "s": "Halloran (The Sentinel)",
   "t": 139.1,
   "x": "Thank you. That goes in paragraph four, verbatim, and we hold the second figure back until it's stood up."
  }
 ],
 "political_english_l07.mp3": [
  {
   "e": 8.45,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy. Political and Global Affairs. Lesson seven: Protests and Rights."
  },
  {
   "e": 23.57,
   "s": "Farrow (The Sentinel)",
   "t": 8.45,
   "x": "We're outside the Ministry of the Interior in the third week of Order 44/12, the ninety-day ban on marches in the Ribera district. With me is Tomas Berhane of the Assembly Rights Network. Mr Berhane, what exactly are you asking for?"
  },
  {
   "e": 43.92,
   "s": "Berhane",
   "t": 23.57,
   "x": "Our claim is narrow. The blanket ban is disproportionate. The ground is Article 14 and the Ministry's own code of practice from 2019, which requires a route-by-route assessment before any restriction. So the demand is equally narrow: replace the ban with a notification procedure and review it at ninety days."
  },
  {
   "e": 50.28,
   "s": "Farrow (The Sentinel)",
   "t": 43.92,
   "x": "The Ministry says the order followed serious disruption. You're not disputing that disruption happened."
  },
  {
   "e": 68.69,
   "s": "Berhane",
   "t": 50.28,
   "x": "We're not. Our claim goes to the breadth of the order, not to the need for it. Ten lawful marches have been refused to prevent one difficult afternoon. And we raised this formally on the third of March. We lodged a petition, we have the date stamp, and we have had no reply."
  },
  {
   "e": 73.97,
   "s": "Farrow (The Sentinel)",
   "t": 68.69,
   "x": "Minister, you've heard the claim. Will the order be extended past ninety days?"
  },
  {
   "e": 85.34,
   "s": "Larrea",
   "t": 73.97,
   "x": "Good morning. What I would say is that the assessments are being drawn up, the district commanders are being consulted, and I would not want to prejudge the outcome of a review that is still running."
  },
  {
   "e": 88.61,
   "s": "Farrow (The Sentinel)",
   "t": 85.34,
   "x": "Is that a no, or is that a not yet?"
  },
  {
   "e": 104.3,
   "s": "Larrea",
   "t": 88.61,
   "x": "It is an answer about process, which is the honest one at this stage. Supporters of the order regard it as a proportionate response to a real risk. Critics regard it as too wide. Both of those views will be in front of me when I decide."
  },
  {
   "e": 115.51,
   "s": "Berhane",
   "t": 104.3,
   "x": "Minister, we are not asking you to endorse the message of any march. We are asking you to apply the code you published yourselves. That is inside your authority this morning."
  },
  {
   "e": 128.21,
   "s": "Larrea",
   "t": 115.51,
   "x": "Then let me give you something rather than nothing. I can commit to publishing the district assessments, in full, when the review reports. What I cannot do standing here is tell you what they will say."
  },
  {
   "e": 131.52,
   "s": "Farrow (The Sentinel)",
   "t": 128.21,
   "x": "And if the review reports and the ban stays?"
  },
  {
   "e": 143.18,
   "s": "Berhane",
   "t": 131.52,
   "x": "Then people will take to the streets, and I want it understood that that will be a consequence of the silence, not a cause of it. We used the channels. We have a receipt and no reply."
  },
  {
   "e": 153.55,
   "s": "Larrea",
   "t": 143.18,
   "x": "I would only add that the right of peaceful assembly is not in question here. The question is a narrow one about routes and dates, and I would rather it stayed narrow."
  },
  {
   "e": 161.26,
   "s": "Farrow (The Sentinel)",
   "t": 153.55,
   "x": "A narrow question with a ninety-day clock on it. Nadia Farrow, for The Sentinel, at the Ministry of the Interior."
  }
 ],
 "political_english_l08.mp3": [
  {
   "e": 28.13,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy. Political and Global Affairs, Lesson Eight: Globalization and Trade. The Coastal Union has announced a nine per cent tariff on refined lithium from the Republic of Marenta, a candidate for accession to the Union. Marenta's trade minister, Mr Abioye, takes questions from Renata Silbermann of The Sentinel, with Velenia's trade attache, Mr Lindqvist, joining by video link."
  },
  {
   "e": 34.49,
   "s": "Silbermann",
   "t": 28.13,
   "x": "Minister, nine per cent on refined lithium. Is that a tariff or a punishment?"
  },
  {
   "e": 43.97,
   "s": "Abioye",
   "t": 34.49,
   "x": "It is an instrument. The Coastal Union has imposed a tariff on one product line, and I would rather describe it accurately than dramatically."
  },
  {
   "e": 48.67,
   "s": "Silbermann",
   "t": 43.97,
   "x": "Accurately, then. From when, and at what rate?"
  },
  {
   "e": 61.68,
   "s": "Abioye",
   "t": 48.67,
   "x": "As notified to us, the nine per cent is phased in over eighteen months, three points a year. That schedule matters. It tells you the intention is adjustment, not closure."
  },
  {
   "e": 77.5,
   "s": "Lindqvist",
   "t": 61.68,
   "x": "If I may add something. Velenian buyers began moving orders away from Marenta before this tariff existed, and not on price. We call it friend-shoring, and yes, it costs our buyers about four per cent more."
  },
  {
   "e": 83.86,
   "s": "Silbermann",
   "t": 77.5,
   "x": "Four per cent for politics. Minister, where is the level playing field in that?"
  },
  {
   "e": 100.46,
   "s": "Abioye",
   "t": 83.86,
   "x": "A level playing field means the same rule applies to everyone in the market. It does not mean everyone arrives in the same shoes. We are not asking for an exemption. We are asking that the certification standard apply to Velenian refiners as well."
  },
  {
   "e": 102.79,
   "s": "Lindqvist",
   "t": 100.46,
   "x": "It does apply to them."
  },
  {
   "e": 118.85,
   "s": "Abioye",
   "t": 102.79,
   "x": "On paper. In practice, our shipments were held up at Port Kessel for eleven days last month, waiting on a document your own refiners file electronically. That is a non-tariff barrier, and it costs us more than nine per cent."
  },
  {
   "e": 122.88,
   "s": "Silbermann",
   "t": 118.85,
   "x": "How much more? Give me a number I can print."
  },
  {
   "e": 127.42,
   "s": "Abioye",
   "t": 122.88,
   "x": "I'd want to see the impact assessment before I put a number on it."
  },
  {
   "e": 131.42,
   "s": "Silbermann",
   "t": 127.42,
   "x": "Your ministry commissioned that assessment in March, Minister."
  },
  {
   "e": 145.92,
   "s": "Abioye",
   "t": 131.42,
   "x": "And it lands in June. You will have it the same day I do. On current figures the delay is costing us in the order of double what the tariff costs us, but I am not giving you a decimal that the assessment has not confirmed."
  },
  {
   "e": 160.39,
   "s": "Lindqvist",
   "t": 145.92,
   "x": "Let me be plain about one thing, because it gets misreported. Velenia is de-risking, not decoupling. We want Marentan lithium in the chain. We also want a second source in it."
  },
  {
   "e": 169.49,
   "s": "Abioye",
   "t": 160.39,
   "x": "Then help us clear the bottleneck at Kessel, and you will have a supplier who can ramp up, rather than one that is quietly pricing itself out."
  }
 ],
 "political_english_l09.mp3": [
  {
   "e": 15.7,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson nine: Soft Power. A pre-signature meeting at Marenta's foreign ministry. Velenia has an offer; Foreign Minister Calder has a problem."
  },
  {
   "e": 26.81,
   "s": "Envoy Ostrand",
   "t": 15.7,
   "x": "Minister, Velenia would fund forty scholarships a year, plus a cultural institute on Rivera Square. No conditions. We simply want to build bridges."
  },
  {
   "e": 35.5,
   "s": "Minister Calder",
   "t": 26.81,
   "x": "It's a generous package, and I don't want to understate it — the scholarships in particular answer a gap we have not been able to close ourselves."
  },
  {
   "e": 38.5,
   "s": "Envoy Ostrand",
   "t": 35.5,
   "x": "I can hear a 'but' arriving, Minister."
  },
  {
   "e": 49.18,
   "s": "Minister Calder",
   "t": 38.5,
   "x": "Not a but. A very small comma. Clause nine gives your ministry a seat on the curriculum board, and I'd be reluctant to sign that in its current wording."
  },
  {
   "e": 53.81,
   "s": "Envoy Ostrand",
   "t": 49.18,
   "x": "The seat is advisory. It costs Marenta nothing at all."
  },
  {
   "e": 66.6,
   "s": "Minister Calder",
   "t": 53.81,
   "x": "You may well be right in practice. My difficulty is narrower than it sounds: The Sentinel will read 'seat' as 'vote', and I'd rather not spend the first month of a good programme explaining the difference."
  },
  {
   "e": 78.55,
   "s": "Delegate Rusk",
   "t": 66.6,
   "x": "The Coastal Union has walked into that one before. Ours was watered down after eighteen months of headlines, and every bit of it was avoidable."
  },
  {
   "e": 81.79,
   "s": "Envoy Ostrand",
   "t": 78.55,
   "x": "So you are asking us to drop clause nine."
  },
  {
   "e": 90.98,
   "s": "Minister Calder",
   "t": 81.79,
   "x": "I'd stop short of that. Could we park it for phase one, run the scholarships, and come back on the institute once there's a track record to point to?"
  },
  {
   "e": 94.78,
   "s": "Envoy Ostrand",
   "t": 90.98,
   "x": "Phase one is a polite way of saying never, Minister."
  },
  {
   "e": 104.26,
   "s": "Minister Calder",
   "t": 94.78,
   "x": "It would be, if I gave you no date. Eighteen months, with a published review, and I'll put my own name on the review. That is not nothing."
  },
  {
   "e": 112.58,
   "s": "Delegate Rusk",
   "t": 104.26,
   "x": "If it helps, the Union would host that review. Neutral room, three capitals, no host advantage."
  },
  {
   "e": 120.58,
   "s": "Envoy Ostrand",
   "t": 112.58,
   "x": "Let me take that back to Velenia. I won't pretend they'll love it. But I'd rather bring them a phased yes than a clean no."
  },
  {
   "e": 129.65,
   "s": "Minister Calder",
   "t": 120.58,
   "x": "That's all I'm asking. And Envoy — the scholarships still start in September either way. That part isn't hostage to clause nine."
  },
  {
   "e": 133.32,
   "s": "Narrator",
   "t": 129.65,
   "x": "Notice what the Minister never once said."
  }
 ],
 "political_english_l10.mp3": [
  {
   "e": 14.4,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson Ten: Treaties and Law. A drafting session on the Marenta–Coastal Union minerals accord, two weeks before signature."
  },
  {
   "e": 25.97,
   "s": "Counsel Vetrano (Coastal Union)",
   "t": 14.4,
   "x": "Minister, Article 11 has come back from our legal service. The obligation to transmit inspection data has been redrafted as permissive, with a practicability qualifier."
  },
  {
   "e": 36.38,
   "s": "Minister Adeyemi (Marenta)",
   "t": 25.97,
   "x": "Then Article 11 no longer creates an obligation. It creates permission. My parliament will not ratify a text that binds us to nothing."
  },
  {
   "e": 44.14,
   "s": "Adviser Lindqvist (Velenia)",
   "t": 36.38,
   "x": "And Velenia would read a practicability qualifier as an escape clause wide enough to drive a convoy through."
  },
  {
   "e": 53.71,
   "s": "Counsel Vetrano (Coastal Union)",
   "t": 44.14,
   "x": "Two of our six members will not sign up to a hard obligation before their own inspection systems are running. That is arithmetic, not bad faith."
  },
  {
   "e": 64.22,
   "s": "Minister Adeyemi (Marenta)",
   "t": 53.71,
   "x": "Then draft the timing, not the verb. Keep 'each party shall transmit', and start it from the thirtieth month. You get your delay; we keep our duty."
  },
  {
   "e": 72.14,
   "s": "Adviser Lindqvist (Velenia)",
   "t": 64.22,
   "x": "That is a phased obligation, and a phased obligation is auditable. Permission is not auditable."
  },
  {
   "e": 75.5,
   "s": "Counsel Vetrano (Coastal Union)",
   "t": 72.14,
   "x": "And if a party misses the thirtieth month?"
  },
  {
   "e": 85.49,
   "s": "Minister Adeyemi (Marenta)",
   "t": 75.5,
   "x": "Then it is in breach, and Annex C applies. That is precisely what the word is for. A treaty that cannot be breached cannot be relied on."
  },
  {
   "e": 92.02,
   "s": "Counsel Vetrano (Coastal Union)",
   "t": 85.49,
   "x": "I will take the phased text back to the six. I cannot promise you consensus by Friday."
  },
  {
   "e": 106.42,
   "s": "Adviser Lindqvist (Velenia)",
   "t": 92.02,
   "x": "One further drafting note. Paragraph two still reads 'the parties shall endeavour to verify'. Endeavour clauses are best-endeavours language; they bind you to trying, not to doing."
  },
  {
   "e": 116.57,
   "s": "Minister Adeyemi (Marenta)",
   "t": 106.42,
   "x": "Strike 'endeavour'. If ministers are asked to sign on the dotted line, they are entitled to know exactly what they are bound to before the cameras arrive."
  },
  {
   "e": 122.66,
   "s": "Counsel Vetrano (Coastal Union)",
   "t": 116.57,
   "x": "Understood. And ratification — when does Marenta deposit its instrument?"
  },
  {
   "e": 133.73,
   "s": "Minister Adeyemi (Marenta)",
   "t": 122.66,
   "x": "Within ninety days of signature, subject to parliament. I can initial it; I cannot ratify it, and I will not commit to a date I do not control."
  },
  {
   "e": 145.7,
   "s": "Adviser Lindqvist (Velenia)",
   "t": 133.73,
   "x": "Then we provisionally apply Articles 1 to 8 from signature and let Article 11 enter into force on ratification. Nobody waits, and nobody pretends."
  },
  {
   "e": 151.97,
   "s": "Counsel Vetrano (Coastal Union)",
   "t": 145.7,
   "x": "Circulate a clean text tonight, and flag every remaining 'may' in the margin."
  }
 ],
 "political_english_l11.mp3": [
  {
   "e": 16.61,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson eleven: Crisis Management. A fire at the Port Solano fuel terminal, Republic of Marenta. It is now fifty minutes since the first emergency call."
  },
  {
   "e": 28.97,
   "s": "Press Secretary Norlin",
   "t": 16.61,
   "x": "Minister, The Sentinel already has a photograph of the smoke plume, and the Coastal Union delegation is asking whether the shipping lane is open. Velenia has offered two fire tugs."
  },
  {
   "e": 36.6,
   "s": "Minister Adeyemi",
   "t": 28.97,
   "x": "Then we go now. An empty podium at fifty minutes is worse than a short statement at fifty minutes."
  },
  {
   "e": 45.34,
   "s": "Press Secretary Norlin",
   "t": 36.6,
   "x": "We still have nothing verified on injuries. Nothing at all. I'd rather wait for the hospital to call us back."
  },
  {
   "e": 54.96,
   "s": "Minister Adeyemi",
   "t": 45.34,
   "x": "Then we say that, and we say it in order. We acknowledge, we say what is already being done, and we give them a time. Nothing else leaves this room."
  },
  {
   "e": 57.91,
   "s": "Press Secretary Norlin",
   "t": 54.96,
   "x": "Cameras are live in forty seconds."
  },
  {
   "e": 76.94,
   "s": "Minister Adeyemi",
   "t": 57.91,
   "x": "Good evening. At 16:12 a fire broke out in tank seven at the Port Solano terminal. Fire crews were on site within eleven minutes, the harbour is closed, and air-quality sampling has begun. I will be back at this podium at nine o'clock."
  },
  {
   "e": 83.45,
   "s": "Halloran, The Sentinel",
   "t": 76.94,
   "x": "Minister — Halloran, The Sentinel. How many people were working on that terminal tonight?"
  },
  {
   "e": 93.82,
   "s": "Minister Adeyemi",
   "t": 83.45,
   "x": "I'm not going to speculate ahead of the facts. What I can confirm at this stage is that the site has been evacuated and every shift supervisor has been accounted for."
  },
  {
   "e": 100.27,
   "s": "Halloran, The Sentinel",
   "t": 93.82,
   "x": "We have unverified reports of two ambulances leaving the north gate. Are you holding that back?"
  },
  {
   "e": 109.68,
   "s": "Minister Adeyemi",
   "t": 100.27,
   "x": "I'm holding nothing back. I'm holding a number until it is verified. You will have it at nine, or you will have me standing here telling you we still don't know."
  },
  {
   "e": 116.88,
   "s": "Halloran, The Sentinel",
   "t": 109.68,
   "x": "With respect, Minister, you leave office in six weeks. Why should anyone take a commitment from a lame duck?"
  },
  {
   "e": 130.68,
   "s": "Minister Adeyemi",
   "t": 116.88,
   "x": "Because the commitment is the ministry's, not mine. The independent review I am commissioning tonight will still be running long after I've gone, and my successor inherits both the review and your questions."
  },
  {
   "e": 135.36,
   "s": "Halloran, The Sentinel",
   "t": 130.68,
   "x": "Nine o'clock, then. Figures, or apologies?"
  },
  {
   "e": 143.47,
   "s": "Minister Adeyemi",
   "t": 135.36,
   "x": "Figures, if they're verified. An honest 'we don't know yet' if they aren't. I'd rather give you a right answer than a fast one."
  }
 ],
 "political_english_l12.mp3": [
  {
   "e": 19.61,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson Twelve: Election Day. The Republic of Marenta's Electoral Commission briefs the press at eleven at night, with eighty-one per cent of ballots counted. Minister Adeyemi has come down to the same room to take questions."
  },
  {
   "e": 33.02,
   "s": "Commissioner Halvard",
   "t": 19.61,
   "x": "Good evening. Eighty-one per cent of ballots have been counted. Turnout stands at sixty-three per cent, up five points on the last cycle. I'll take three questions."
  },
  {
   "e": 39.43,
   "s": "Wray (The Sentinel)",
   "t": 33.02,
   "x": "Commissioner, two networks have already called the race. Will you sign off on that tonight?"
  },
  {
   "e": 49.92,
   "s": "Commissioner Halvard",
   "t": 39.43,
   "x": "A broadcaster makes a projection. This Commission makes a declaration. We will not be declaring anything until the coastal districts have reported."
  },
  {
   "e": 54.86,
   "s": "Wray (The Sentinel)",
   "t": 49.92,
   "x": "The gap is 4.1 points. Is that a landslide?"
  },
  {
   "e": 60.0,
   "s": "Commissioner Halvard",
   "t": 54.86,
   "x": "It is a lead. I'll leave the adjectives to your subeditors."
  },
  {
   "e": 67.22,
   "s": "Wray (The Sentinel)",
   "t": 60.0,
   "x": "Minister Adeyemi, your bloc has pulled ahead in eleven of the fourteen districts. Are you claiming victory?"
  },
  {
   "e": 75.67,
   "s": "Minister Adeyemi",
   "t": 67.22,
   "x": "I'm claiming nothing at eleven o'clock at night. What I would say is that the trend has been consistent since the first boxes were opened."
  },
  {
   "e": 78.02,
   "s": "Wray (The Sentinel)",
   "t": 75.67,
   "x": "Has Ms Torvald called you?"
  },
  {
   "e": 85.82,
   "s": "Minister Adeyemi",
   "t": 78.02,
   "x": "I've had no call. And I'd add that nobody should read anything into that — there are counts still running in two provinces."
  },
  {
   "e": 95.4,
   "s": "Commissioner Halvard",
   "t": 85.82,
   "x": "For the record, three districts have requested a recount of spoiled ballots. That is routine and it does not hold up certification."
  },
  {
   "e": 101.76,
   "s": "Wray (The Sentinel)",
   "t": 95.4,
   "x": "And if the margin narrows overnight? Would you rule out a challenge, Minister?"
  },
  {
   "e": 109.39,
   "s": "Minister Adeyemi",
   "t": 101.76,
   "x": "I'm not going to answer a question about a scenario that hasn't happened. Ask me again once the Commission has certified."
  },
  {
   "e": 112.46,
   "s": "Wray (The Sentinel)",
   "t": 109.39,
   "x": "Commissioner, when is that, realistically?"
  },
  {
   "e": 121.13,
   "s": "Commissioner Halvard",
   "t": 112.46,
   "x": "Thursday at the earliest. Until then, every figure you hear tonight, including mine, is provisional."
  }
 ],
 "political_english_l13.mp3": [
  {
   "e": 14.47,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy - Political and Global Affairs. Lesson thirteen: Political Parties. A Sentinel correspondent has Minister Adeyemi and a Renewal Front spokesman on the same call."
  },
  {
   "e": 21.5,
   "s": "Halloran (The Sentinel)",
   "t": 14.47,
   "x": "Minister, Deputy Oyelaran crossed the floor on Tuesday. Does the government still command a working majority?"
  },
  {
   "e": 29.4,
   "s": "Minister Adeyemi",
   "t": 21.5,
   "x": "The arithmetic has changed by one seat. I'd rather not dramatise a single decision by a single deputy."
  },
  {
   "e": 32.62,
   "s": "Halloran (The Sentinel)",
   "t": 29.4,
   "x": "One seat is the entire margin, Minister."
  },
  {
   "e": 39.17,
   "s": "Minister Adeyemi",
   "t": 32.62,
   "x": "It is a narrow margin. It was narrow last week as well, and we passed three bills with it."
  },
  {
   "e": 44.57,
   "s": "Halloran (The Sentinel)",
   "t": 39.17,
   "x": "Mr Beluri, the Renewal Front gained that deputy. What was she promised?"
  },
  {
   "e": 53.54,
   "s": "Beluri (Renewal Front)",
   "t": 44.57,
   "x": "Nothing was promised. Her account is that our platform is where she has always stood, and that her own party is the one that moved."
  },
  {
   "e": 58.9,
   "s": "Minister Adeyemi",
   "t": 53.54,
   "x": "That is her account. I'd attribute it to her rather than treat it as a finding."
  },
  {
   "e": 65.21,
   "s": "Halloran (The Sentinel)",
   "t": 58.9,
   "x": "Mr Beluri, describe your position on mining royalties for a Velenian reader who doesn't know our labels."
  },
  {
   "e": 75.53,
   "s": "Beluri (Renewal Front)",
   "t": 65.21,
   "x": "Somewhere to the left of the National Compact and to the right of the Smallholders' League. Our critics call that indecision; we'd call it a broad church."
  },
  {
   "e": 83.21,
   "s": "Halloran (The Sentinel)",
   "t": 75.53,
   "x": "Minister, your own backbenchers are split on the same bill. Two of them told The Sentinel the royalty rate has been watered down."
  },
  {
   "e": 91.49,
   "s": "Minister Adeyemi",
   "t": 83.21,
   "x": "Every governing party contains factions. Ours are unusually articulate and occasionally unusually loud."
  },
  {
   "e": 94.22,
   "s": "Halloran (The Sentinel)",
   "t": 91.49,
   "x": "Will they fall into line on Thursday?"
  },
  {
   "e": 103.87,
   "s": "Minister Adeyemi",
   "t": 94.22,
   "x": "Party discipline is not something I promise on the record. What I will say is that the bill goes to the floor on Thursday and I expect it to pass."
  },
  {
   "e": 110.38,
   "s": "Beluri (Renewal Front)",
   "t": 103.87,
   "x": "And if it doesn't, the Coastal Union delegation lands on Friday to meet a government that can't count."
  }
 ],
 "political_english_l14.mp3": [
  {
   "e": 7.97,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson fourteen: The Campaign Trail."
  },
  {
   "e": 18.29,
   "s": "Ruvane",
   "t": 7.97,
   "x": "Minister, I've timed your draft. Four minutes twenty. The hall in Kessel Bay will give you ninety seconds before the phones come out."
  },
  {
   "e": 26.09,
   "s": "Adeyemi",
   "t": 18.29,
   "x": "The detail matters, Ms Ruvane. The port financing alone has three phases and a review clause."
  },
  {
   "e": 33.98,
   "s": "Ruvane",
   "t": 26.09,
   "x": "You've given me nine priorities, Minister. Nine is a list. Three is a promise."
  },
  {
   "e": 37.51,
   "s": "Adeyemi",
   "t": 33.98,
   "x": "Then choose the three for me and I will defend them."
  },
  {
   "e": 48.53,
   "s": "Ruvane",
   "t": 37.51,
   "x": "I won't choose. You will, because you have to say them the same way in every hall between here and the vote. That is what it means to stay on message."
  },
  {
   "e": 51.02,
   "s": "Adeyemi",
   "t": 48.53,
   "x": "Ports, clinics, courts."
  },
  {
   "e": 57.82,
   "s": "Ruvane",
   "t": 51.02,
   "x": "Again — but hang a reason on each one. Same rhythm, same opening word."
  },
  {
   "e": 67.01,
   "s": "Adeyemi",
   "t": 57.82,
   "x": "Ports, because trade pays for everything else. Clinics, because growth has to reach the coast road. Courts, because neither can be bought."
  },
  {
   "e": 73.34,
   "s": "Ruvane",
   "t": 67.01,
   "x": "That's the spine. Now the contrast. What are the others offering?"
  },
  {
   "e": 87.41,
   "s": "Adeyemi",
   "t": 73.34,
   "x": "Supporters of the Coastal Union package say it is finance Marenta cannot raise alone; critics counter that the conditions cost more than the money. I would rather not adjudicate that from a stage."
  },
  {
   "e": 114.12,
   "s": "Ruvane",
   "t": 87.41,
   "x": "Then don't. Say: they promise more, we promise three, costed and dated. That is your soundbite, and nothing longer survives the evening bulletin. And when the other side takes your three nouns and says them back at you — they will, by Thursday — you do not go hunting for new ones. You keep the three and move the argument onto who signs, who audits, and who pays when it slips."
  },
  {
   "e": 124.82,
   "s": "Sallow",
   "t": 114.12,
   "x": "Minister — Nadia Sallow, The Sentinel. A memo from your own ministry has the port timetable slipping to 2032. Your comment?"
  },
  {
   "e": 134.33,
   "s": "Adeyemi",
   "t": 124.82,
   "x": "I'm not going to be drawn on a document I haven't seen. Ports, clinics, courts. Those three carry dates, and I'll defend the dates."
  },
  {
   "e": 139.01,
   "s": "Sallow",
   "t": 134.33,
   "x": "That is the third time this evening you have said those three words, Minister."
  },
  {
   "e": 142.03,
   "s": "Adeyemi",
   "t": 139.01,
   "x": "Then it is working, Ms Sallow."
  }
 ],
 "political_english_l15.mp3": [
  {
   "e": 20.38,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson fifteen: Public Opinion and Polling. The Sentinel has published new figures on Marenta's water tariff bill. Correspondent Petra Calder questions the pollster, Doctor Ilan Maroque, and then Minister Adeyemi."
  },
  {
   "e": 30.48,
   "s": "Calder",
   "t": 20.38,
   "x": "Doctor Maroque, your poll puts support for the tariff bill at forty-one per cent and opposition at thirty-eight. Has the country turned against the government?"
  },
  {
   "e": 44.83,
   "s": "Maroque",
   "t": 30.48,
   "x": "I'd be careful with that. With a sample size of one thousand and two adults, the margin of error is about three points either way. Forty-one and thirty-eight is a statistical dead heat."
  },
  {
   "e": 48.43,
   "s": "Calder",
   "t": 44.83,
   "x": "So you're telling me the three-point lead isn't real."
  },
  {
   "e": 60.55,
   "s": "Maroque",
   "t": 48.43,
   "x": "It may well be real. It simply isn't measured. Once you factor in the margin, support could be as low as thirty-eight and opposition as high as forty-one."
  },
  {
   "e": 66.12,
   "s": "Calder",
   "t": 60.55,
   "x": "Your response rate was eleven per cent. Doesn't that undermine the whole exercise?"
  },
  {
   "e": 80.47,
   "s": "Maroque",
   "t": 66.12,
   "x": "It's the honest weakness of my industry. We use a weighted sample to correct for who picks up the phone, and we weed out respondents who fail the attention checks, but weighting is a repair, not a cure."
  },
  {
   "e": 86.42,
   "s": "Calder",
   "t": 80.47,
   "x": "The Sentinel ran a straw poll of forty readers last week and got the opposite result."
  },
  {
   "e": 107.52,
   "s": "Maroque",
   "t": 86.42,
   "x": "Then your forty readers have told you something interesting about your forty readers. Our tracking poll has asked the identical question every fortnight since March. Support rose, then levelled off in June, and has barely moved since. That is the trend, and the trend is what holds up."
  },
  {
   "e": 113.59,
   "s": "Calder",
   "t": 107.52,
   "x": "Minister Adeyemi, you've seen the numbers. Has the public turned against your bill?"
  },
  {
   "e": 126.79,
   "s": "Adeyemi",
   "t": 113.59,
   "x": "I'd want the fieldwork dates in front of me before I said anything that dramatic. What I will say is that a movement of two or three points is noise, and I'm not going to read too much into a single poll."
  },
  {
   "e": 132.34,
   "s": "Calder",
   "t": 126.79,
   "x": "It isn't a single poll any more. Four surveys now point the same way."
  },
  {
   "e": 143.86,
   "s": "Adeyemi",
   "t": 132.34,
   "x": "Four surveys from three houses, and I'd note that two of them buy from the same online panel. If the direction is borne out through the autumn, we will listen carefully."
  },
  {
   "e": 150.0,
   "s": "Calder",
   "t": 143.86,
   "x": "And if it isn't? Supporters say the public simply hasn't heard the detail of the bill."
  },
  {
   "e": 160.73,
   "s": "Adeyemi",
   "t": 150.0,
   "x": "Supporters do say that. Critics counter that the public has heard it perfectly well and disliked it. I'm not going to settle that argument from a table of percentages."
  },
  {
   "e": 164.38,
   "s": "Calder",
   "t": 160.73,
   "x": "So the ministry's position is unchanged."
  }
 ],
 "political_english_l16.mp3": [
  {
   "e": 8.38,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson sixteen: Scandals and Ethics."
  },
  {
   "e": 19.85,
   "s": "Brennell (The Sentinel)",
   "t": 8.38,
   "x": "Minister, we've published an email dated the ninth, from your private office to the evaluation panel, about the coastal monitoring contract. Did you see that email before the contract was signed?"
  },
  {
   "e": 31.49,
   "s": "Minister Adeyemi",
   "t": 19.85,
   "x": "Let me be absolutely clear, because a great deal of nonsense has been printed this week. I have never instructed any official to favour one bidder over another."
  },
  {
   "e": 38.86,
   "s": "Brennell (The Sentinel)",
   "t": 31.49,
   "x": "That isn't what I asked. I didn't ask whether you gave an instruction. I asked whether you saw the email."
  },
  {
   "e": 47.42,
   "s": "Minister Adeyemi",
   "t": 38.86,
   "x": "What the department has acknowledged is an irregularity in the sequencing of the procurement. That is being looked into."
  },
  {
   "e": 53.78,
   "s": "Brennell (The Sentinel)",
   "t": 47.42,
   "x": "You mean the contract was signed before the panel had finished. Can we use that sentence instead?"
  },
  {
   "e": 64.13,
   "s": "Nadia Brekke (Ministry press office)",
   "t": 53.78,
   "x": "The Minister has set out the position. The file has been handed over to an independent inquiry, and we won't be running a parallel process at this table."
  },
  {
   "e": 72.94,
   "s": "Brennell (The Sentinel)",
   "t": 64.13,
   "x": "Then a different question. The official who gave us the file — are they still employed, and are they being treated as a whistleblower or as a leaker?"
  },
  {
   "e": 84.7,
   "s": "Minister Adeyemi",
   "t": 72.94,
   "x": "The disclosure was made through the protected channel, so the officer keeps their post and their anonymity. I want that on the record, and I want it repeated to every official in the building."
  },
  {
   "e": 92.3,
   "s": "Brennell (The Sentinel)",
   "t": 84.7,
   "x": "Noted. Our readers will still want to know why a Velenian supplier appears to have been told the outcome two days early."
  },
  {
   "e": 100.27,
   "s": "Minister Adeyemi",
   "t": 92.3,
   "x": "You are hunting for a smoking gun, and what you have is a badly worded calendar entry made by a junior official."
  },
  {
   "e": 108.17,
   "s": "Brennell (The Sentinel)",
   "t": 100.27,
   "x": "A badly worded calendar entry with your private office's name on it, Minister. Will the inquiry see the unredacted version?"
  },
  {
   "e": 115.03,
   "s": "Nadia Brekke (Ministry press office)",
   "t": 108.17,
   "x": "Everything goes to the inquiry. Publication is a matter for the panel, not for us."
  },
  {
   "e": 122.81,
   "s": "Brennell (The Sentinel)",
   "t": 115.03,
   "x": "One commitment before we close, Minister. Will you publish the full timeline of who signed off on the contract, with dates?"
  },
  {
   "e": 133.37,
   "s": "Minister Adeyemi",
   "t": 122.81,
   "x": "I'll give you the sign-off timeline in writing by Thursday. Dates and names, not a summary. If any part of it turns out to be wrong, I'll correct it publicly."
  }
 ],
 "political_english_l17.mp3": [
  {
   "e": 17.11,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson seventeen: Nations and Borders. A scheduled press briefing at the Marentan foreign ministry, three days after a new customs post opened at the eastern end of the Ossara Corridor."
  },
  {
   "e": 27.48,
   "s": "Fenwick (The Sentinel)",
   "t": 17.11,
   "x": "Minister, there is now a Velenian customs post at Ossara East, staffed by Velenian officers, flying a Velenian flag. Does Marenta accept that?"
  },
  {
   "e": 41.4,
   "s": "Minister Adeyemi",
   "t": 27.48,
   "x": "I accept what your photographers have filmed. Officers are there; the post is operating. Whether Marenta accepts the arrangement is a different sentence, and I would ask you not to run the two together."
  },
  {
   "e": 46.49,
   "s": "Fenwick (The Sentinel)",
   "t": 41.4,
   "x": "Then let me run them apart. Who does that stretch of ground belong to?"
  },
  {
   "e": 62.9,
   "s": "Minister Adeyemi",
   "t": 46.49,
   "x": "Who staffs a customs post and whose sovereignty it sits under are two different questions, and I will not merge them for you. Marenta's position on the second is unchanged, and everything we do at that crossing is without prejudice to it."
  },
  {
   "e": 76.46,
   "s": "Envoy Voss (Velenia)",
   "t": 62.9,
   "x": "If I may. Velenia has exercised sovereignty over the Ossara Corridor for thirty-one years, and we have said so in every forum that will have us. The post is administration, not adventure."
  },
  {
   "e": 81.1,
   "s": "Fenwick (The Sentinel)",
   "t": 76.46,
   "x": "Envoy, has the Coastal Union extended recognition to that arrangement?"
  },
  {
   "e": 92.69,
   "s": "Envoy Voss (Velenia)",
   "t": 81.1,
   "x": "Recognition is a matter for each member individually. Two have said the arrangement is orderly. Four are holding off, which is their right, and we have not asked them to hurry."
  },
  {
   "e": 106.73,
   "s": "Minister Adeyemi",
   "t": 92.69,
   "x": "The Union pools sovereignty on tariffs, not on borders. No official in that building can recognise anything on behalf of six governments, and I would be careful about reading silence as consent."
  },
  {
   "e": 113.21,
   "s": "Fenwick (The Sentinel)",
   "t": 106.73,
   "x": "Minister, our front page this morning said you had drawn a line in the sand at Ossara. Had you?"
  },
  {
   "e": 126.0,
   "s": "Minister Adeyemi",
   "t": 113.21,
   "x": "Your front page is livelier than my brief. A line in the sand is a deadline with a threat behind it; what we have set out is a claim with a map behind it. I would ask you to print the difference."
  },
  {
   "e": 138.86,
   "s": "Envoy Voss (Velenia)",
   "t": 126.0,
   "x": "Velenia staked out its position in nineteen ninety-four and has not moved. We are not asking Marenta to back down publicly. We are asking that the crossing stay open while the lawyers argue."
  },
  {
   "e": 143.11,
   "s": "Fenwick (The Sentinel)",
   "t": 138.86,
   "x": "So will Marenta hold off on any formal step until the next round?"
  },
  {
   "e": 161.74,
   "s": "Minister Adeyemi",
   "t": 143.11,
   "x": "We will hold off on nothing, because there is nothing to announce. The transit protocol runs until March, it is an interim measure pending a negotiated settlement, and we take no position on the underlying claim. Operating a crossing is a rota, not a policy."
  },
  {
   "e": 166.34,
   "s": "Fenwick (The Sentinel)",
   "t": 161.74,
   "x": "One more. In one sentence, what changed this week?"
  },
  {
   "e": 178.13,
   "s": "Minister Adeyemi",
   "t": 166.34,
   "x": "A building opened. As a matter of principle, not of preference, Marenta responds to buildings with paperwork, not with declarations. Thank you, that is all."
  }
 ],
 "political_english_l18.mp3": [
  {
   "e": 20.59,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson eighteen: Environmental Policy. A midday briefing room at the Coastal Union environment council. Minister Okwuosa, Marenta's environment minister, Envoy Halvorsen of Velenia, and Ines Dravec of The Sentinel."
  },
  {
   "e": 29.18,
   "s": "Dravec",
   "t": 20.59,
   "x": "Minister, the communiqué says Marenta accepts a forty per cent cut by 2040. Is that binding, or is it an aspiration?"
  },
  {
   "e": 38.16,
   "s": "Okwuosa",
   "t": 29.18,
   "x": "The figure is in the text, and Marenta does not put figures in texts it intends to ignore. What is still open is the instrument."
  },
  {
   "e": 41.5,
   "s": "Dravec",
   "t": 38.16,
   "x": "So the target is agreed and the mechanism isn't."
  },
  {
   "e": 50.33,
   "s": "Okwuosa",
   "t": 41.5,
   "x": "The target is agreed. The mechanism is drafted. The cost line is what three delegations are still reading very slowly."
  },
  {
   "e": 63.0,
   "s": "Halvorsen",
   "t": 50.33,
   "x": "Velenia's position is straightforward. A carbon price floor is the cleanest instrument available. It is transparent, it is predictable, and it does not require anyone to trust anyone else's inventory."
  },
  {
   "e": 79.15,
   "s": "Okwuosa",
   "t": 63.0,
   "x": "Predictable for whom, Envoy? A floor set at Velenian price levels is predictable in Velenia. In a country still phasing out two coal plants, it is an abatement cost of roughly four per cent of industrial output in year one."
  },
  {
   "e": 83.57,
   "s": "Halvorsen",
   "t": 79.15,
   "x": "And the just transition fund exists precisely to absorb that."
  },
  {
   "e": 94.92,
   "s": "Okwuosa",
   "t": 83.57,
   "x": "The fund exists on paper. It is capitalised in 2032. The compliance timetable begins in 2029. My question is only about those three years."
  },
  {
   "e": 105.89,
   "s": "Dravec",
   "t": 94.92,
   "x": "Envoy, supporters of the floor call it the fairest option available; critics counter that it front-loads the cost onto the smallest economies in the bloc. Which description do you accept?"
  },
  {
   "e": 113.9,
   "s": "Halvorsen",
   "t": 105.89,
   "x": "Both can be true at once. What Velenia cannot accept is a fund that grows every single time the timetable is reopened."
  },
  {
   "e": 124.3,
   "s": "Okwuosa",
   "t": 113.9,
   "x": "With respect, when the baseline year moved from 2015 to 2019 last spring, nobody in this room called that moving the goalposts."
  },
  {
   "e": 127.97,
   "s": "Halvorsen",
   "t": 124.3,
   "x": "That was a technical correction to the inventory method."
  },
  {
   "e": 133.15,
   "s": "Okwuosa",
   "t": 127.97,
   "x": "Every adjustment is technical to the delegation that proposes it."
  },
  {
   "e": 139.51,
   "s": "Dravec",
   "t": 133.15,
   "x": "Minister, one line for tomorrow's front page. Will Marenta sign in June?"
  },
  {
   "e": 148.44,
   "s": "Okwuosa",
   "t": 139.51,
   "x": "Marenta will sign a target in June. Whether Marenta signs a cost in June depends entirely on what is written between now and then."
  }
 ],
 "political_english_l19.mp3": [
  {
   "e": 22.3,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson nineteen: Immigration and Borders. The Sentinel interviews Marenta's interior minister, Kofi Odame, and the Coastal Union's migration commissioner, Petra Nordhagen. Marenta is a candidate for accession to the Union, not a member of it."
  },
  {
   "e": 31.61,
   "s": "Barros (The Sentinel)",
   "t": 22.3,
   "x": "Minister Odame, we have the ministry's own figure: forty-one thousand irregular arrivals in eleven months. Is Marenta's border out of control?"
  },
  {
   "e": 43.1,
   "s": "Minister Odame",
   "t": 31.61,
   "x": "I'd resist the framing of that question, Ms Barros. Forty-one thousand is applications lodged, not people crossing; about a quarter of those are renewals from the same caseload."
  },
  {
   "e": 46.66,
   "s": "Barros (The Sentinel)",
   "t": 43.1,
   "x": "A distinction your critics will call a technicality."
  },
  {
   "e": 57.79,
   "s": "Minister Odame",
   "t": 46.66,
   "x": "It is the difference between a denominator and a headline. Against a workforce of four point one million, that is one per cent — and our harvest sector is short eleven thousand hands."
  },
  {
   "e": 72.65,
   "s": "Commissioner Nordhagen",
   "t": 57.79,
   "x": "The Union's position is that Marenta cannot be asked to absorb an entire corridor alone. We have tabled a burden-sharing arrangement: six member capitals, one quota, with Marenta at the table as an accession partner rather than a member."
  },
  {
   "e": 79.54,
   "s": "Barros (The Sentinel)",
   "t": 72.65,
   "x": "Six capitals that have not agreed a quota since the bloc was founded. Isn't this simply a political football?"
  },
  {
   "e": 91.99,
   "s": "Commissioner Nordhagen",
   "t": 79.54,
   "x": "It is kicked around, yes. That is precisely why the pilot is technical rather than declaratory: three thousand seasonal visas, phased in over two years, with a readmission annex."
  },
  {
   "e": 98.35,
   "s": "Barros (The Sentinel)",
   "t": 91.99,
   "x": "Velenia's envoy briefed us that Marenta waves people through and then bills the Union. Minister?"
  },
  {
   "e": 109.92,
   "s": "Minister Odame",
   "t": 98.35,
   "x": "I won't respond to a briefing I have not seen in writing. What I will say is that nobody is waved through: every applicant is fingerprinted, interviewed, and given a decision date."
  },
  {
   "e": 113.71,
   "s": "Barros (The Sentinel)",
   "t": 109.92,
   "x": "Nine months away, according to your own inspectorate."
  },
  {
   "e": 128.11,
   "s": "Minister Odame",
   "t": 113.71,
   "x": "Nine months is the backlog we inherited. Supporters of the pilot argue that a regular pathway shortens it; critics counter that it advertises the route. Both claims are testable, and we intend to test them."
  },
  {
   "e": 134.78,
   "s": "Commissioner Nordhagen",
   "t": 128.11,
   "x": "And on pushes — the drought in the eastern corridor is not something anyone in this room can legislate away."
  },
  {
   "e": 141.74,
   "s": "Barros (The Sentinel)",
   "t": 134.78,
   "x": "Commissioner, one line for tomorrow's front page: will the Union take in people, or only fund the fence?"
  },
  {
   "e": 150.19,
   "s": "Commissioner Nordhagen",
   "t": 141.74,
   "x": "Both, and I would rather be quoted on the sequence than on a slogan: pathways first, enforcement alongside, and neither one on its own."
  }
 ],
 "political_english_l20.mp3": [
  {
   "e": 19.18,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson twenty: The Social Contract. The Sentinel interviews Minister Adeyemi of the Republic of Marenta, with Dr Nystrom, a constitutional adviser seconded from Velenia to the Coastal Union secretariat."
  },
  {
   "e": 30.29,
   "s": "Ferrante (The Sentinel)",
   "t": 19.18,
   "x": "Minister, Article 9 imposes five years of civic service on every citizen under thirty. It was never put to a referendum. On what basis do you say the public has accepted it?"
  },
  {
   "e": 47.95,
   "s": "Adeyemi",
   "t": 30.29,
   "x": "I would resist the framing of acceptance as a single event, Ms Ferrante. The position of the government is that continued participation in the electoral process constitutes tacit consent to the constitutional framework within which parliament legislates."
  },
  {
   "e": 56.74,
   "s": "Ferrante (The Sentinel)",
   "t": 47.95,
   "x": "So a citizen who was a child when Article 9 was drafted in 2014 consents to five years of service by voting in a municipal election in 2023?"
  },
  {
   "e": 69.12,
   "s": "Adeyemi",
   "t": 56.74,
   "x": "It commits them to the framework, not to any particular measure within it. That distinction is not a technicality; it is the whole architecture of representative government."
  },
  {
   "e": 87.53,
   "s": "Nystrom",
   "t": 69.12,
   "x": "May I introduce a distinction the literature treats as fundamental? Consent that cannot be withheld is not consent; it is acquiescence. If a citizen has no procedure by which to refuse, the Minister's premise does no work — it merely describes the absence of an exit."
  },
  {
   "e": 101.06,
   "s": "Adeyemi",
   "t": 87.53,
   "x": "Dr Nystrom speaks from a country of two million people with a very short border. In Marenta, some burdens are simply carried for the greater good, and I make no apology for saying so."
  },
  {
   "e": 114.77,
   "s": "Ferrante (The Sentinel)",
   "t": 101.06,
   "x": "Then let me put the objection in its strongest form. Suppose, for the sake of argument, that we accepted tacit consent as sufficient. Were that principle applied consistently, what measure could this parliament not impose without asking anyone?"
  },
  {
   "e": 123.48,
   "s": "Adeyemi",
   "t": 114.77,
   "x": "That is a fair question and I will not fall back on generalities. There are limits, and they are the ones the courts enforce."
  },
  {
   "e": 136.94,
   "s": "Nystrom",
   "t": 123.48,
   "x": "With respect, Minister, judicial limits address legality. The gap Ms Ferrante is pointing at is a legitimacy deficit, and no court in Marenta or the Coastal Union has ever closed one of those by ruling."
  },
  {
   "e": 151.34,
   "s": "Adeyemi",
   "t": 136.94,
   "x": "Then let us speak about duty in both directions. If the state asks for five years, the state owes training, wages and a guaranteed return to employment. That is a reciprocal duty and it will be honoured."
  },
  {
   "e": 159.77,
   "s": "Ferrante (The Sentinel)",
   "t": 151.34,
   "x": "Will it? The 2024 housing commitments were never delivered. Why should anyone believe the government will follow through on this one?"
  },
  {
   "e": 176.11,
   "s": "Adeyemi",
   "t": 159.77,
   "x": "Because the obligation cuts both ways this time, and because a conscientious exemption will be written into the enabling legislation. Those who object on grounds of belief will be able to opt out of the service requirement without penalty."
  },
  {
   "e": 187.32,
   "s": "Nystrom",
   "t": 176.11,
   "x": "Had the drafters offered that exemption at the outset, the consent argument would have been considerably stronger. It is being offered now because the legitimacy question would not go away."
  },
  {
   "e": 192.41,
   "s": "Ferrante (The Sentinel)",
   "t": 187.32,
   "x": "Minister, does the objection you have heard this morning stand up to scrutiny — yes or no?"
  },
  {
   "e": 203.18,
   "s": "Adeyemi",
   "t": 192.41,
   "x": "It stands up to scrutiny. It does not follow that it defeats the article. We will publish the exemption clause on Thursday and the public may judge."
  }
 ],
 "political_english_l21.mp3": [
  {
   "e": 15.36,
   "s": "Narrator",
   "t": 0.24,
   "x": "Vesper Academy, Political and Global Affairs. Lesson twenty-one: Geopolitics — The Silicon Shield. A joint press availability in Marenta's capital, following Velenia's licensing review."
  },
  {
   "e": 27.58,
   "s": "Halloran (The Sentinel)",
   "t": 15.36,
   "x": "Minister Adeyemi, Velenia makes the advanced chips inside three-quarters of the Coastal Union's grid equipment, and Marenta refines the minerals those chips depend on. Isn't that a chokepoint on both sides?"
  },
  {
   "e": 38.69,
   "s": "Minister Adeyemi",
   "t": 27.58,
   "x": "I'd call it a shared dependency, and I would very much like it to stay boring. A chokepoint only becomes a flashpoint when somebody decides to squeeze it."
  },
  {
   "e": 49.9,
   "s": "Envoy Rask (Velenia)",
   "t": 38.69,
   "x": "Velenia's position is straightforward. Our export controls are narrow, targeted and reviewable. Nothing in them is directed at Marenta."
  },
  {
   "e": 54.6,
   "s": "Halloran (The Sentinel)",
   "t": 49.9,
   "x": "You did phase out licences for two Marentan refiners last quarter, though."
  },
  {
   "e": 65.3,
   "s": "Envoy Rask (Velenia)",
   "t": 54.6,
   "x": "We phased out licences for two lines of dual-use equipment. The refiners may reapply under the new framework, and the framework is published."
  },
  {
   "e": 74.47,
   "s": "Minister Adeyemi",
   "t": 65.3,
   "x": "We have asked for that framework in writing. I'm not going to characterise Velenia's intentions; I'll characterise the paperwork, which is late."
  },
  {
   "e": 82.13,
   "s": "Halloran (The Sentinel)",
   "t": 74.47,
   "x": "Minister, the Coastal Union parliament is debating whether to ratchet up its own restrictions. Would Marenta retaliate?"
  },
  {
   "e": 93.46,
   "s": "Minister Adeyemi",
   "t": 82.13,
   "x": "I'd be reluctant to use that word. If access were withdrawn, we would be obliged to consider the options available to us. That is not a threat; it is arithmetic."
  },
  {
   "e": 107.86,
   "s": "Envoy Rask (Velenia)",
   "t": 93.46,
   "x": "May I add something. Deterrence here is not about capability. Both of us can hurt each other rather easily. It's about making sure neither of us ever has a reason to."
  },
  {
   "e": 118.39,
   "s": "Halloran (The Sentinel)",
   "t": 107.86,
   "x": "Some analysts argue that technological dependence is a kind of shield — nobody attacks the factory they rely on. Critics counter that it just turns the factory into a target."
  },
  {
   "e": 132.31,
   "s": "Minister Adeyemi",
   "t": 118.39,
   "x": "Both readings are defensible, and I'd rather not adjudicate between them at a microphone. What I will say is that we should not lock in a structure where one bad quarter can escalate into a crisis."
  },
  {
   "e": 141.72,
   "s": "Envoy Rask (Velenia)",
   "t": 132.31,
   "x": "Which is exactly why Velenia has proposed a standing technical channel at official level, meeting monthly, whatever the political temperature."
  },
  {
   "e": 149.57,
   "s": "Minister Adeyemi",
   "t": 141.72,
   "x": "Marenta will take that proposal seriously. And I'd ask The Sentinel to report the channel, not only the friction."
  },
  {
   "e": 155.09,
   "s": "Halloran (The Sentinel)",
   "t": 149.57,
   "x": "Noted, Minister. Although the friction does sell rather more papers."
  }
 ]
};
