// Auto-generated by build_basics_audio_data.py - Core Basics listening tracks
window.BASICS_DATA = {
  "1": {
    "tag": "Foundations (A0)",
    "icon": "fa-seedling",
    "lessons": [
      {
        "n": 1,
        "title": "Who Are You?",
        "file": "core_basics_level_1_lesson_1.mp3"
      },
      {
        "n": 2,
        "title": "Where Are You From?",
        "file": "core_basics_level_1_lesson_2.mp3"
      },
      {
        "n": 3,
        "title": "Jobs & Professions",
        "file": "core_basics_level_1_lesson_3.mp3"
      },
      {
        "n": 4,
        "title": "Adjectives (Feelings)",
        "file": "core_basics_level_1_lesson_4.mp3"
      },
      {
        "n": 5,
        "title": "Family Tree",
        "file": "core_basics_level_1_lesson_5.mp3"
      },
      {
        "n": 6,
        "title": "Colors & Clothing",
        "file": "core_basics_level_1_lesson_6.mp3"
      },
      {
        "n": 7,
        "title": "Describing People",
        "file": "core_basics_level_1_lesson_7.mp3"
      },
      {
        "n": 8,
        "title": "The Weather",
        "file": "core_basics_level_1_lesson_8.mp3"
      },
      {
        "n": 9,
        "title": "Numbers 1-20",
        "file": "core_basics_level_1_lesson_9.mp3"
      },
      {
        "n": 10,
        "title": "Time & Days",
        "file": "core_basics_level_1_lesson_10.mp3"
      },
      {
        "n": 11,
        "title": "Rooms in House",
        "file": "core_basics_level_1_lesson_11.mp3"
      },
      {
        "n": 12,
        "title": "Prepositions of Place",
        "file": "core_basics_level_1_lesson_12.mp3"
      },
      {
        "n": 13,
        "title": "There is / There are",
        "file": "core_basics_level_1_lesson_13.mp3"
      },
      {
        "n": 14,
        "title": "Demonstratives (This/That)",
        "file": "core_basics_level_1_lesson_14.mp3"
      },
      {
        "n": 15,
        "title": "Possessive Adjectives",
        "file": "core_basics_level_1_lesson_15.mp3"
      },
      {
        "n": 16,
        "title": "Nationalities",
        "file": "core_basics_level_1_lesson_16.mp3"
      },
      {
        "n": 17,
        "title": "Opposites",
        "file": "core_basics_level_1_lesson_17.mp3"
      },
      {
        "n": 18,
        "title": "Question Words",
        "file": "core_basics_level_1_lesson_18.mp3"
      },
      {
        "n": 19,
        "title": "Yes/No Questions",
        "file": "core_basics_level_1_lesson_19.mp3"
      }
    ]
  },
  "2": {
    "tag": "Action (A1)",
    "icon": "fa-person-running",
    "lessons": [
      {
        "n": 1,
        "title": "Daily Routine (Present Simple - I Do)",
        "file": "core_basics_level_2_lesson_1.mp3"
      },
      {
        "n": 2,
        "title": "Third Person (He Does)",
        "file": "core_basics_level_2_lesson_2.mp3"
      },
      {
        "n": 3,
        "title": "Questions (Do vs Does)",
        "file": "core_basics_level_2_lesson_3.mp3"
      },
      {
        "n": 4,
        "title": "Adverbs of Frequency",
        "file": "core_basics_level_2_lesson_4.mp3"
      },
      {
        "n": 5,
        "title": "Object Pronouns",
        "file": "core_basics_level_2_lesson_5.mp3"
      },
      {
        "n": 6,
        "title": "Hobbies (Like + ing)",
        "file": "core_basics_level_2_lesson_6.mp3"
      },
      {
        "n": 7,
        "title": "Past Tense (Past Simple)",
        "file": "core_basics_level_2_lesson_7.mp3"
      },
      {
        "n": 8,
        "title": "Regular Verbs in the Past (-ed)",
        "file": "core_basics_level_2_lesson_8.mp3"
      },
      {
        "n": 9,
        "title": "Irregular Verbs in the Past",
        "file": "core_basics_level_2_lesson_9.mp3"
      },
      {
        "n": 10,
        "title": "Review: Past Verbs",
        "file": "core_basics_level_2_lesson_10.mp3"
      },
      {
        "n": 11,
        "title": "Going to a Restaurant",
        "file": "core_basics_level_2_lesson_11.mp3"
      },
      {
        "n": 12,
        "title": "Activities at Home",
        "file": "core_basics_level_2_lesson_12.mp3"
      },
      {
        "n": 13,
        "title": "Future with Will",
        "file": "core_basics_level_2_lesson_13.mp3"
      },
      {
        "n": 14,
        "title": "Listening Clips Practice",
        "file": "core_basics_level_2_lesson_14.mp3"
      },
      {
        "n": 15,
        "title": "Imperative Sentences",
        "file": "core_basics_level_2_lesson_15.mp3"
      },
      {
        "n": 16,
        "title": "Can & Can't",
        "file": "core_basics_level_2_lesson_16.mp3"
      },
      {
        "n": 17,
        "title": "Different Ways to Invite",
        "file": "core_basics_level_2_lesson_17.mp3"
      },
      {
        "n": 18,
        "title": "Continuous vs Simple (Now vs Usually)",
        "file": "core_basics_level_2_lesson_18.mp3"
      },
      {
        "n": 19,
        "title": "Review & Practice",
        "file": "core_basics_level_2_lesson_19.mp3"
      }
    ]
  },
  "3": {
    "tag": "Experience (A2)",
    "icon": "fa-compass",
    "lessons": [
      {
        "n": 1,
        "title": "Present Continuous",
        "file": "core_basics_level_3_lesson_1.mp3"
      },
      {
        "n": 2,
        "title": "Present Simple vs Continuous",
        "file": "core_basics_level_3_lesson_2.mp3"
      },
      {
        "n": 3,
        "title": "Present Perfect (Experiences)",
        "file": "core_basics_level_3_lesson_3.mp3"
      },
      {
        "n": 4,
        "title": "Past Simple Review (Storytelling)",
        "file": "core_basics_level_3_lesson_4.mp3"
      },
      {
        "n": 5,
        "title": "Going to (Future Plans)",
        "file": "core_basics_level_3_lesson_5.mp3"
      },
      {
        "n": 6,
        "title": "Comparatives",
        "file": "core_basics_level_3_lesson_6.mp3"
      },
      {
        "n": 7,
        "title": "Superlatives",
        "file": "core_basics_level_3_lesson_7.mp3"
      },
      {
        "n": 8,
        "title": "Asking for Information (WH Questions)",
        "file": "core_basics_level_3_lesson_8.mp3"
      },
      {
        "n": 9,
        "title": "Modal Verbs (Should / Must / Have to)",
        "file": "core_basics_level_3_lesson_9.mp3"
      },
      {
        "n": 10,
        "title": "Zero and First Conditionals",
        "file": "core_basics_level_3_lesson_10.mp3"
      },
      {
        "n": 11,
        "title": "Second Conditional (Hypothetical)",
        "file": "core_basics_level_3_lesson_11.mp3"
      },
      {
        "n": 12,
        "title": "Passive Voice (Introduction)",
        "file": "core_basics_level_3_lesson_12.mp3"
      },
      {
        "n": 13,
        "title": "Reported Speech (Introduction)",
        "file": "core_basics_level_3_lesson_13.mp3"
      },
      {
        "n": 14,
        "title": "Relative Clauses",
        "file": "core_basics_level_3_lesson_14.mp3"
      },
      {
        "n": 15,
        "title": "Phrasal Verbs (Common Set)",
        "file": "core_basics_level_3_lesson_15.mp3"
      },
      {
        "n": 16,
        "title": "Expressing Opinions",
        "file": "core_basics_level_3_lesson_16.mp3"
      },
      {
        "n": 17,
        "title": "Describing People and Places",
        "file": "core_basics_level_3_lesson_17.mp3"
      },
      {
        "n": 18,
        "title": "Talking About Health",
        "file": "core_basics_level_3_lesson_18.mp3"
      },
      {
        "n": 19,
        "title": "Shopping and Negotiating",
        "file": "core_basics_level_3_lesson_19.mp3"
      }
    ]
  },
  "4": {
    "tag": "Writing (A2+)",
    "icon": "fa-pen-nib",
    "lessons": [
      {
        "n": 1,
        "title": "The Mechanics (S+V) & The Pronunciation War",
        "file": "core_basics_level_4_lesson_1.mp3"
      },
      {
        "n": 2,
        "title": "Punctuation Marks",
        "file": "core_basics_level_4_lesson_2.mp3"
      },
      {
        "n": 3,
        "title": "Capitalization Rules",
        "file": "core_basics_level_4_lesson_3.mp3"
      },
      {
        "n": 4,
        "title": "Linking Words (And, But, So)",
        "file": "core_basics_level_4_lesson_4.mp3"
      },
      {
        "n": 5,
        "title": "Sequencing (First, Then)",
        "file": "core_basics_level_4_lesson_5.mp3"
      },
      {
        "n": 6,
        "title": "Paragraph Structure",
        "file": "core_basics_level_4_lesson_6.mp3"
      },
      {
        "n": 7,
        "title": "Writing Emails",
        "file": "core_basics_level_4_lesson_7.mp3"
      },
      {
        "n": 8,
        "title": "Adjective Order",
        "file": "core_basics_level_4_lesson_8.mp3"
      },
      {
        "n": 9,
        "title": "Relative Clauses (Who/Which)",
        "file": "core_basics_level_4_lesson_9.mp3"
      },
      {
        "n": 10,
        "title": "Opinion Essays",
        "file": "core_basics_level_4_lesson_10.mp3"
      },
      {
        "n": 11,
        "title": "Past Simple vs Continuous (Narrative)",
        "file": "core_basics_level_4_lesson_11.mp3"
      },
      {
        "n": 12,
        "title": "Used To (Past Habits)",
        "file": "core_basics_level_4_lesson_12.mp3"
      },
      {
        "n": 13,
        "title": "Present Perfect (For/Since)",
        "file": "core_basics_level_4_lesson_13.mp3"
      },
      {
        "n": 14,
        "title": "Passives (Intro)",
        "file": "core_basics_level_4_lesson_14.mp3"
      },
      {
        "n": 15,
        "title": "Second Conditional (Unreal)",
        "file": "core_basics_level_4_lesson_15.mp3"
      },
      {
        "n": 16,
        "title": "Too / Enough",
        "file": "core_basics_level_4_lesson_16.mp3"
      },
      {
        "n": 17,
        "title": "Indirect Questions",
        "file": "core_basics_level_4_lesson_17.mp3"
      },
      {
        "n": 18,
        "title": "Future Forms Review",
        "file": "core_basics_level_4_lesson_18.mp3"
      },
      {
        "n": 19,
        "title": "Prepositions of Movement",
        "file": "core_basics_level_4_lesson_19.mp3"
      }
    ]
  }
};
